global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["10.0.1.15:9110"]

  - job_name: "grafana"
    metrics_path: /metrics
    static_configs:
      - targets: ["10.0.1.7:3000"]